name: Deploy Environments

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Code
        uses: actions/checkout@v4

      # Si estamos en la rama main (Producción), el archivo se queda en la raíz
      # Si estamos en la rama develop (Desarrollo), creamos la subcarpeta /dev
       Madre de la automatización limpia
      - name: Organize Folders Based on Branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            mkdir -p dev
            cp index.html dev/
            rm index.html
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
